# Generated by Django 5.1.7 on 2026-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('house_type', models.CharField(max_length=100)),
                ('posted', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_days', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('semi_furnished', models.BooleanField(default=False)),
                ('fully_furnished', models.BooleanField(default=False)),
                ('brand_new', models.BooleanField(default=False)),
                ('private_gate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
