# Generated by Django 6.0.1 on 2026-02-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalhouse',
            name='brand_new',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='fully_furnished',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='posted_days',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='private_gate',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='semi_furnished',
        ),
        migrations.RemoveField(
            model_name='rentalhouse',
            name='url',
        ),
    ]
