# Generated by Django 6.0 on 2026-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rentalhouse_brand_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='rentalhouse',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalhouse',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalhouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
